version: '3.8'

networks:
    dock:
        driver: bridge

volumes:
    dock-mysql:
        driver: local

services:

    php:
        build:
            context: .
            dockerfile: .docker/php.dockerfile
        restart: unless-stopped
        ports:
            - 8080:80
        volumes:
            - .:/app
        networks:
            - dock

    schedule:
        build:
            context: .
            dockerfile: .docker/php.dockerfile
        restart: unless-stopped
        command:
            - "schedule:work"
        volumes:
            - .:/app
        networks:
            - dock

    worker:
        build:
            context: .
            dockerfile: .docker/php.dockerfile
        restart: unless-stopped
        command:
            - "queue:listen"
            - "--queue=app,playstation,notifications"
        volumes:
            - .:/app
        networks:
            - dock

    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'dock-mysql:/var/lib/mysql'
        networks:
            - dock
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s

